# Generated by Django 3.0.6 on 2020-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=1024)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
