# Generated by Django 3.0.6 on 2020-06-02 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256)),
                ("body", models.TextField()),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("published", models.DateField(default=datetime.date.today)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("tags", models.ManyToManyField(to="blog.Tag")),
            ],
        ),
    ]
