# Generated by Django 3.1.1 on 2020-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20200607_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(
                default="The description for this article needs to be set.",
                max_length=256,
            ),
            preserve_default=False,
        ),
    ]
