# Generated by Django 3.1.4 on 2020-12-17 21:57

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_article_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=5096)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("approved", models.BooleanField(default=False)),
                (
                    "token",
                    models.CharField(default=secrets.token_urlsafe, max_length=256),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.article"
                    ),
                ),
            ],
        ),
    ]
