# Generated by Django 3.1.1 on 2020-09-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=256)),
                ("audio_url", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=256)),
                ("published", models.DateTimeField()),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("transcript", models.TextField()),
            ],
            options={"ordering": ("-season", "-number"),},
        ),
    ]
